[package]
name = "colorbot"
version = "0.1.0"
edition = "2021"
description = "A OSRS color bot"
license = "Unlicense"

[dependencies]
rand = "0.8.5"
kurbo = "0.11.1"
scrap = "0.5.0"
serde = {version = "1.0.215", features = ["derive"]}
serde_json = "1.0.133"
